### ISSUE TITLE
VM property vm_id is not available via the virtual_machine_scale_set_vms.list

### ISSUE THREAD

**Issue by klcsig** [Azure/azure-sdk-ruby#15]
With version 0.3.1, the vm_id was made available when you call virtual_machine.get ( see the azure_mgmt_compute/models/virtual_machine_properties.rb)
When the you call virtual_machine_scale_set_vms.list, the vm.properties does not include the vm_id. Please add this property in  azure_mgmt_compute/models/virtual_machine_scale_set_vmproperties.rb)

**Comment by vishrutshah** [comment]
@klcsig Thanks a lot for the valuable feedback. [azure_mgmt_compute](https://rubygems.org/gems/azure_mgmt_compute) sdk is generated from the swagger specification defined at [arm-compute/2016-03-30/swagger/compute.json](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L4285ruby) 

I'd recommend opening an issue related to the modeling of sdk at [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/issues) so that it can be fixed in all the compute sdk for all supported languages.

**Comment by veronicagg** [comment]
Request is open in the azure-rest-api-specs repo, as the property should be added in the specification.
